server:
  port: 8099

spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sevenWeb?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: 123456
#    热部署配置
  devtools:
    restart:
      enabled: true  #设置开启热部署
      additional-paths: src/main/java #重启目录
      exclude: WEB-INF/**

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.seven.web.model
